<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1a1a2e; padding: 30px; }

        .header { margin-bottom: 24px; border-bottom: 2px solid #3b82f6; padding-bottom: 14px; }
        .header h1 { font-size: 20px; font-weight: 700; color: #1e3a8a; }
        .header p  { font-size: 11px; color: #6b7280; margin-top: 3px; }
        .badge {
            display: inline-block;
            padding: 2px 10px;
            border-radius: 20px;
            font-size: 10px;
            font-weight: 600;
            margin-left: 8px;
            vertical-align: middle;
        }
        .badge-weekly  { background: #dbeafe; color: #1d4ed8; }
        .badge-monthly { background: #ede9fe; color: #6d28d9; }

        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        thead tr { background: #1e3a8a; color: #fff; }
        thead th { padding: 9px 12px; text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; }
        .col-desc { max-width: 180px; word-break: break-word; }
        tbody tr:nth-child(even) { background: #f8faff; }
        tbody tr:nth-child(odd)  { background: #ffffff; }
        tbody td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }

        .status-completed { color: #059669; font-weight: 600; }
        .status-active    { color: #d97706; font-weight: 600; }

        .summary {
            margin-top: 20px;
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            border-radius: 6px;
            padding: 12px 16px;
            display: flex;
            justify-content: space-between;
        }
        .summary-item { font-size: 11px; color: #374151; }
        .summary-item strong { color: #1e3a8a; font-size: 13px; }

        .footer { margin-top: 28px; font-size: 9px; color: #9ca3af; text-align: right; }
    </style>
</head>
<body>

    <div class="header">
        <h1>
            Time Logs Report
            <span class="badge badge-{{ $type }}">{{ ucfirst($type) }}</span>
        </h1>
        <p>Period: {{ $label }} &nbsp;|&nbsp; Generated: {{ \Carbon\Carbon::now()->format('M d, Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Employee</th>
                <th>Date</th>
                <th>Clock In</th>
                <th>Clock Out</th>
                <th>Total Hours</th>
                <th>Description</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($logs as $log)
            @php $bill = $log->total_hours ? $log->total_hours * $log->user->hourly_rate : 0; @endphp
            <tr>
                <td>{{ $log->user->name }}</td>
                <td>{{ $log->date->format('M d, Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($log->clock_in)->format('h:i A') }}</td>
                <td>{{ $log->clock_out ? \Carbon\Carbon::parse($log->clock_out)->format('h:i A') : '—' }}</td>
                <td>{{ $log->total_hours ? $log->total_hours . ' hrs' : '—' }}</td>
                <td class="col-desc">{{ $log->description ?: '—' }}</td>
                <td>
                    @if($log->clock_out)
                        <span class="status-completed">Completed</span>
                    @else
                        <span class="status-active">Active</span>
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align:center; padding: 20px; color:#9ca3af;">No logs found for this period.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <div class="summary-item">Total Records: <strong>{{ $logs->count() }}</strong></div>
        <div class="summary-item">Total Hours: <strong>{{ number_format($totalHours, 2) }} hrs</strong></div>
        <div class="summary-item">Hourly Rate: <strong>${{ number_format($logs->first()->user->hourly_rate ?? 0, 2) }}</strong></div>
        <div class="summary-item">Total Bill: <strong>${{ number_format($logs->sum(fn($l) => $l->total_hours * $l->user->hourly_rate), 2) }}</strong></div>
    </div>

    <div class="footer">Generated by TimeTracker &mdash; Confidential</div>

</body>
</html>